### ISSUE TITLE
Suggest integrate with git config

### ISSUE THREAD

**Issue by akerust** [Prodesire/terminal-proxy#1]
Hi, I found `http_proxy` and `https_proxy` from os environ don't work in some circumstances, e.g. launch vscode directly, extension such as `go` installs its dependencies from vscode inside through `git` , then it will bypass these settings.

I work around it by scripts below:

```bash
export socks_url="http://127.0.0.1:1087"

set_git_proxy() {
    git config --global http.proxy $socks_url
    git config --global https.proxy $socks_url
}

unset_git_proxy() {
    git config --global --unset http.proxy
    git config --global --unset https.proxy
}

echo_git_proxy() {
    echo "[http.proxy]"
    git config --global http.proxy
    echo "[https.proxy]"
    git config --global https.proxy
}
```

Now just turn on git proxy globally with `set_git_proxy`, install or upgrade components anywhere, and end up with `unset_git_proxy`.

Hope this helps, best regards~

**Comment by Prodesire** [comment]
Good idea! I will support this feature soon.

**Comment by Prodesire** [comment]
Please update to 0.2.0!
